### ISSUE TITLE
/booster queue display broken

### ISSUE THREAD

**Issue by Mythyryn** [CecerMCProjects/HypixelUtils#9]
When you /booster queue with the mod enabled, the active boosters show before the line that says "Network Booster Queue" and none are clickable and formatted wrong, although the games with no boosters are shown correctly in the proper spot beneath the "Network Booster Queue" line.
![2015-01-31_20 55 41](https://cloud.githubusercontent.com/assets/9811307/5990846/135040cc-a98c-11e4-807b-1ce232cf1650.png)

**Comment by Cecer** [comment]
Fixed in V1.2.3
